version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=musicbeer

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dannacapera16@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "82:82"
    depends_on:
      - postgres
